### ISSUE TITLE
Example not work

### ISSUE THREAD

**Issue by exdeniz** [kentcdodds/prettier-eslint#2]
I try run example
```
const format = require('prettier-eslint')

// notice, no semicolon in the original text
const sourceCode = 'const {foo} = bar'

const options = {
  text: sourceCode,
  eslintConfig: {
    rules: {
      semi: ['error', 'never'],
    },
  },
  prettierOptions: {
    bracketSpacing: true,
  },
}

const formatted = format(options)

// notice no semicolon in the formatted text
console.log(formatted) // const { foo } = bar
```
and output "undefined"

**Comment by kentcdodds** [comment]
Hmmm... Weird. I can look into it another time. But you're welcome to dig a little too figure out why that's happening :-)

**Comment by demoneaux** [comment]
Seems like you're running `format(options)` without passing in the code to format.

**Comment by exdeniz** [comment]
@demoneaux I try now code
```
const format = require('prettier-eslint')
const sourceCode = `const {foo} = bar`

// notice, no semicolon in the original text
const options = {
  eslintConfig: {
    rules: {
      semi: ['error', 'never'],
    },
  },
  prettierOptions: {
    bracketSpacing: true,
  },
}

const formatted = format(sourceCode, options)

// notice no semicolon in the formatted text
console.log(formatted) // const { foo } = bar
```
and return
```
prettier-eslint error: prettier formatting failed TypeError: Cannot read property '0' of undefined
    at new Parser (/Users/exdeniz/Project/temp/test/node_modules/babylon/lib/index.js:1529:45)
    at Object.parse (/Users/exdeniz/Project/temp/test/node_modules/babylon/lib/index.js:6657:10)
    at Object.format (/Users/exdeniz/Project/temp/test/node_modules/prettier-eslint/node_modules/prettier/index.js:42:21)
    at prettify (/Users/exdeniz/Project/temp/test/node_modules/prettier-eslint/dist/index.js:64:31)
    at format (/Users/exdeniz/Project/temp/test/node_modules/prettier-eslint/dist/index.js:55:18)
    at Object.<anonymous> (/Users/exdeniz/Project/temp/test/app.js:16:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by exdeniz** [comment]
I found work example, but eslintConfig not working, use rules for eslintrc. 
```
const format = require('prettier-eslint')
const sourceCode = 'const {foo} = bar'

// notice, no semicolon in the original text
const eslintConfig = {
    rules: {
      semi: ['error', 'never'],
    }
    }
  const prettierOptions = {
    bracketSpacing: true,
  }

const formatted = format({ text: sourceCode, eslintConfig: eslintConfig, prettierOptions: prettierOptions })

// notice no semicolon in the formatted text
console.log(formatted) // const { foo } = bar
```

**Comment by kentcdodds** [comment]
Could you take a look at this? https://github.com/kentcdodds/prettier-eslint/pull/4
